defaults: &defaults
  working_directory: ~/gifted
  docker:
    - image: circleci/node:12.6.0

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build react app
          command: yarn build
          environment:
            REACT_APP_API_URL: ${REACT_APP_API_URL}
            REACT_APP_GIPHY_TOKEN: ${REACT_APP_GIPHY_TOKEN}

      - persist_to_workspace:
          root: .
          paths:
            - build

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn install
      - run: yarn test

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: sudo npm install --global --unsafe-perm now
      - deploy:
          name: Deploy & Alias
          command: |
            now build --token $ZEIT_TOKEN --target production

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
